const  ActionTypes = {
    FETCH_USERS_DATA_SUCCESS : 'FETCH_USERS_DATA_SUCCESS',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POST_DETAILS_SUCCESS: 'FETCH_POST_DETAILS_SUCCESS',
    FETCH_USER_COMMENTS_SUCCESS: 'FETCH_USER_COMMENTS_SUCCESS',
    FETCH_POST_COMMENTS_SUCCESS: 'FETCH_POST_COMMENTS_SUCCESS',
    FETCH_USER_DATA_SUCCESS: 'FETCH_USER_DATA_SUCCESS'
};

export default ActionTypes;
